project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Final Project —— Housing Prices, Crime rate and Racial Geography In Philadelphia"
  page-footer:
    left: "Yuqiushi@upenn.edu"
    right: "This page is built with the talented free will of Capybara and [Quarto](https://quarto.org/) for the good of Philly."

  sidebar:
    logo: "images/bara1.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/raederhans
        text: "Raederhans Github Page"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/Project File.ipynb 

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
